[package]
name = "things3"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
osascript = "0.3.0"
serde = { version = "1.0.152", features = ["derive"] }
